name: Manual Deploy

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create package-lock.json
        run: npm install --package-lock-only

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          mkdir -p build
          cp public/* build/ || true
          echo "<html><head><title>SailRoute Planner</title></head><body><h1>SailRoute Planner</h1><p>Bienvenido a SailRoute Planner</p></body></html>" > build/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
